on: pull_request

jobs:
  readme_comment_pr:
    runs-on: ubuntu-latest
    name: Add a comment on the PR for the README
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1

        with:
          message: "View the README here:  xxx"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
