name: Create readme comment on PR
on: pull_request

jobs:
  readme_comment_pr:
    runs-on: ubuntu-latest
    name: Add a comment on the PR for the README
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "./"
      - name: Install yarn
        run: npm install -g yarn
      - name: Yarn install, build, and test
        run: |
          yarn install  --frozen-lockfile
      - name: "Get README path"
        id: readme
        run: |
          echo "::set-output name=path::$(node ./branch_pip_path.js)"
      - name: "Comment PR"
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            View README here: ${{ github.server_url }}/${{ github.repository }}/tree/${{ github.head_ref }}/Proposed/${{ steps.readme.outputs.path }}#readme
